export const SET_LAYOUT = "SET_LAYOUT";

export const FETCH_PLAYERS = "FETCH_PLAYERS";
export const SET_PLAYERS = "SET_PLAYERS";
export const FETCH_PLAYERS_ERROR = "FETCH_PLAYERS_ERROR";

export const SET_PLAYER = "SET_PLAYER";
export const FETCH_PLAYER = "FETCH_PLAYER";
export const FETCH_PLAYER_ERROR = "FETCH_PLAYER_ERROR";

export const SET_STOCKS = "SET_STOCKS";
export const FETCH_STOCKS = "FETCH_STOCKS";
export const FETCH_STOCKS_ERROR = "FETCH_STOCKS_ERROR";

export const SET_STOCK = "SET_STOCK";
export const FETCH_STOCK = "FETCH_STOCK";
export const FETCH_STOCK_ERROR = "FETCH_STOCK_ERROR";
