export const SET_LAYOUT = "SET_LAYOUT";

export const FETCH_PLAYERS = "FETCH_PLAYERS";
export const SET_PLAYERS = "SET_PLAYERS";
export const FETCH_PLAYERS_ERROR = "FETCH_PLAYERS_ERROR";

export const SET_PLAYER = "SET_PLAYER";
export const FETCH_PLAYER = "FETCH_PLAYER";
export const FETCH_PLAYER_ERROR = "FETCH_PLAYER_ERROR";

export const SET_STOCKS = "SET_STOCKS";
export const FETCH_STOCKS = "FETCH_STOCKS";
export const FETCH_STOCKS_ERROR = "FETCH_STOCKS_ERROR";

export const SET_STOCK = "SET_STOCK";
export const FETCH_STOCK = "FETCH_STOCK";
export const FETCH_STOCK_ERROR = "FETCH_STOCK_ERROR";

export const POST_OFFER = "POST_OFFER";
export const POST_OFFER_ERROR = "POST_OFFER_ERROR";

export const SET_USER = "SET_USER";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

export const POST_REGISTRATION = "POST_REGISTRATION";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const POST_LOGIN = "POST_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";